Repository udoyhasan/useful-code-snippets, pull requests merged in 2022-10, with the labels that each got.

#1 Added an example code file
  python/hello-world.py
Labels: hacktoberfest, hacktober-accepted

#2 Added Patterns.py
  python/Patterns.py
Labels: hacktoberfest, missing details

#5 cpp codes added
  CPP/BinaryToDecimal.cpp
  CPP/DecimalToBinary.cpp
  CPP/DiiferenceOf2Arrays.cpp
  CPP/Merge2SortedArray.cpp
  CPP/MoveZeroes.cpp
  CPP/PairSum.cpp
  CPP/SelectionSort.cpp
  CPP/UniqueElement.cpp
  CPP/additionOf2Arrays.cpp
  CPP/insertionSort.cpp
Labels: missing details

#6 Nqueens program added
  CPP/Nqueens.cpp
Labels: hacktoberfest, hacktoberfest-accepted
